# Run the following command to setup the conda env:
#   conda env create -f requirements.yml --name compling && conda clean --all --yes

channels:
  - pytorch
dependencies:
  - python>=3.7
  - pytorch=1.2
  - transformers
  - spacy
  - textacy
  - urllib
  - bs4